### ISSUE TITLE
Self-intersections in NeuGen-created cells

### ISSUE THREAD

**Issue by bsumirak** [NeuroBox3D/NeuGen#29] opened 2017-01-30 18:10 UTC
Cells created by NeuGen often contain several self-intersections. This is due to at least the following critical points:

- acute angles (local self-intersection),
- branching points where branching dendrite is almost parallel to original one,
- bad luck (nothing seems to prevent a new dendrite from going right through an existing one).

While this is not an issue for 1d simulations, it is if one tries to re-interpret the point/diameter information as a real 3d cell surface (using, e.g., AnaMorph). It would be preferable to create cells that are not self-intersecting (and thus more realistic). This should be relatively inexpensive.

I suppose (without having checked) that there are also intersections between neurons when creating networks. Avoiding this kind of intersection might be more involved (would probably require using some spatial indexing structure for dismissing definitely not intersecting segments fast).

**Comment by stephanmg** [comment] 2017-01-30 19:25
@bsumirak thanks for your suggestions/comments.
if you would like to address this please assign you in the Assignees panel.

Preferably we want to branch of from master a new feature branch resolveSI.

**Comment by bsumirak** [comment] 2017-01-30 19:29
@stephanmg Haha, guess I "forgot" that because I saw the minimal possibility that someone might step up and do it. :P

**Comment by stephanmg** [comment] 2020-08-27 07:07
YAGNI, thus closing this issue. Feel free to open is the problem is acute.

**Closed as completed by stephanmg** 2020-08-27 07:07 UTC
Labels: enhancement
